integration:
  gateway:
    chatgpt:
      timeouts:
        rest:
          socket-timeout: 120
          connection-timeout: 120
          connection-request-timeout: 120
      number-of-connections-pool: 20
      number-of-connections-pool-per-route: 20
      model: gpt-3.5-turbo-1106
      base-uri: https://api.openai.com/v1/chat/completions
      api-key: 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
    dalle:
      model: dall-e-3
      base-uri: https://api.openai.com/v1/images/generations
      api-key: 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
    maps:
      places:
        endpoint-text-search: https://maps.googleapis.com/maps/api/place/textsearch/json
        endpoint-details: https://maps.googleapis.com/maps/api/place/details/json
        api-key: AIzaSyCI1fWshdzjt6duD1oftwVk8FECV92VoRs
    google-search:
      endpoint: https://www.googleapis.com/customsearch/v1?
      api-key: AIzaSyDI8i1fKP2Hztqtt8JOqY-Vmnz_Dw5cDLo
      cx: a022e7c8cfbdd4596
    web-scraping:
      endpoint: https://api.webscrapingapi.com/v1?
      api-key: dMbVtXBoB4yaNBDv6dYBDmzVS7oWcHMw
      render-js: 0
      proxy-type: datacenter