integration:
  gateway:
    chatgpt:
      timeouts:
        rest:
          socket-timeout: 90
          connection-timeout: 90
          connection-request-timeout: 90
      number-of-connections-pool: 20
      number-of-connections-pool-per-route: 20
      model: gpt-3.5-turbo
      base-uri: https://api.openai.com/v1/chat/completions
      api-key: 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